# ========================================================================
# AstLib - Библиотека для Ast плагинов | Конфигурация
# ========================================================================
#
# Телеграмм канал: https://t.me/asteris_plugins
#
# В плагине полная поддержка форматов цвета:
# - Legacy: &a, &l
# - HEX: &#FAEDCB
# - MiniMessage: <gradient:#FAEDCB:#C9E4DE>Текст</gradient>
# ========================================================================

messages:
  startup: "&a[AstLib] Библиотека успешно загружена!"
  shutdown: "&c[AstLib] Библиотека выключена!"
  vault-not-found: "&c[AstLib] Vault не найден! Экономика отключена."
  db-connected: "&a[AstLib] Успешное подключение к базе данных!"
  db-error: "&c[AstLib] Ошибка подключения к базе данных!"
  no-permission: "&cУ вас недостаточно прав для выполнения этой команды!"

# Настройки форматирования времени
time-format:
  days: "д."
  hours: "ч."
  minutes: "м."
  seconds: "с."

# База данных MySQL
mysql:
  enable: false
  host: "localhost" # Хост
  port: 3306 # Порт MySQL сервера
  database: "" # Название базы данных (она уже должна быть создана в phpMyAdmin)
  username: "" # Имя пользователя
  password: "" # Пароль

  pool-size: 10 # Максимальное количество одновременных подключений в пуле HikariCP.
  max-lifetime: 1800000 # Максимальное время жизни одного подключения в миллисекундах.